#[derive(Debug, PartialEq, Eq, Clone, Copy)]
struct MoldUDP64PacketHeader {
    session: [u8; 10],
    sequence_number: u64,
    message_count: u16
}


fn parse_header(body: &[u8]) -> Option<(MoldUDP64PacketHeader, &[u8])> {
    let (message_header, message_body) = body.split_at_checked(20)?;
    Some((
        MoldUDP64PacketHeader {
            session: message_header[..10].try_into().ok()?,
            sequence_number: u64::from_be_bytes(message_header[10..18].try_into().ok()?),
            message_count: u16::from_be_bytes(message_header[18..20].try_into().ok()?)
        },
        message_body
    ))
}


fn parse_messages(message_body: &[u8], message_count: u16, mut handle: impl FnMut(&[u8])) {
    let mut buf = message_body;
    for _ in 0..message_count {
        let Some((message_length_bytes, rest)) = buf.split_at_checked(2) else { return };
        let message_length = u16::from_be_bytes(message_length_bytes.try_into().unwrap()) as usize;
        let Some((message_data, rest)) = rest.split_at_checked(message_length) else { return };
        handle(message_data);
        buf = rest;
    }
}

#[derive(Debug, PartialEq)]
enum PacketStatus {
    NewSession { previous: Option<[u8; 10]> },
    InOrder,
    Gap {start: u64, count: u64},
    StaleOrDuplicate,
    EndOfSession,
}

struct Session {
    session_id: Option<[u8; 10]>,
    expected_sequence_number: u64,
}

impl Session {
    fn new() -> Self {
        Self { session_id: None, expected_sequence_number: 0 }
    }

    fn on_packet(&mut self, packet_header: &MoldUDP64PacketHeader) -> PacketStatus {
        let sequence_number = packet_header.sequence_number;
        let is_end_of_session = packet_header.message_count == 0xFFFF;
        let advance_by = if is_end_of_session {0} else {packet_header.message_count as u64};
        let end = sequence_number + advance_by;

        if self.session_id != Some(packet_header.session) {
            let previous = self.session_id.replace(packet_header.session);
            self.expected_sequence_number = end;
            return PacketStatus::NewSession { previous };
        }

        if is_end_of_session {
            return PacketStatus::EndOfSession;
        }

        if sequence_number == self.expected_sequence_number {
            self.expected_sequence_number = end;
            PacketStatus::InOrder
        } else if sequence_number > self.expected_sequence_number {
            let old_expected_sequence_number = self.expected_sequence_number;
            let gap = sequence_number - self.expected_sequence_number;
            self.expected_sequence_number = end;
            PacketStatus::Gap {
                start: old_expected_sequence_number,
                count: gap
            }
        } else {
            // Assume that retransmission requests cover exactly the requested
            // range, so that even if there is partial overlap, it counts as
            // fully stale
            PacketStatus::StaleOrDuplicate
        }
    }
}

fn build_packet(session: [u8; 10], sequence_number: u64, messages: &[&[u8]]) -> Vec<u8> {
    let message_count = messages.len() as u16;
    let mut buf = Vec::with_capacity(20);
    buf.extend_from_slice(&session);
    buf.extend_from_slice(&sequence_number.to_be_bytes());
    buf.extend_from_slice(&message_count.to_be_bytes());
    for message in messages {
        buf.extend_from_slice(&(message.len() as u16).to_be_bytes());
        buf.extend_from_slice(message);
    }
    buf
}

// <Generated by Claude.ai>
#[cfg(test)]
mod tests {
    use super::*;

    fn session_id(byte: u8) -> [u8; 10] {
        [byte; 10]
    }

    fn header_bytes(session: [u8; 10], sequence_number: u64, message_count: u16) -> Vec<u8> {
        let mut buf = Vec::with_capacity(20);
        buf.extend_from_slice(&session);
        buf.extend_from_slice(&sequence_number.to_be_bytes());
        buf.extend_from_slice(&message_count.to_be_bytes());
        buf
    }

    fn message_block(payload: &[u8]) -> Vec<u8> {
        let mut buf = Vec::with_capacity(2 + payload.len());
        buf.extend_from_slice(&(payload.len() as u16).to_be_bytes());
        buf.extend_from_slice(payload);
        buf
    }

    // ---- parse_header ----

    #[test]
    fn parse_header_valid_with_trailing_body() {
        let mut packet = header_bytes(session_id(1), 42, 3);
        packet.extend_from_slice(b"trailing");

        let (header, rest) = parse_header(&packet).expect("should parse");
        assert_eq!(header, MoldUDP64PacketHeader {
            session: session_id(1),
            sequence_number: 42,
            message_count: 3,
        });
        assert_eq!(rest, b"trailing");
    }

    #[test]
    fn parse_header_exact_20_bytes_leaves_empty_body() {
        let packet = header_bytes(session_id(1), 1, 0);
        let (_, rest) = parse_header(&packet).expect("should parse");
        assert!(rest.is_empty());
    }

    #[test]
    fn parse_header_truncated_returns_none() {
        let packet = vec![0u8; 19];
        assert!(parse_header(&packet).is_none());
    }

    #[test]
    fn parse_header_empty_returns_none() {
        assert!(parse_header(&[]).is_none());
    }

    // ---- parse_messages ----

    #[test]
    fn parse_messages_collects_all_blocks_in_order() {
        let mut body = Vec::new();
        body.extend(message_block(b"AAPL"));
        body.extend(message_block(b"MSFT"));
        body.extend(message_block(b""));

        let mut seen = Vec::new();
        parse_messages(&body, 3, |msg| seen.push(msg.to_vec()));

        assert_eq!(seen, vec![b"AAPL".to_vec(), b"MSFT".to_vec(), b"".to_vec()]);
    }

    #[test]
    fn parse_messages_zero_count_calls_handle_zero_times() {
        let body = message_block(b"unused");
        let mut calls = 0;
        parse_messages(&body, 0, |_| calls += 1);
        assert_eq!(calls, 0);
    }

    #[test]
    fn parse_messages_stops_silently_when_length_prefix_truncated() {
        let body = vec![0u8]; // one byte, can't even read a u16 length
        let mut calls = 0;
        parse_messages(&body, 5, |_| calls += 1);
        assert_eq!(calls, 0);
    }

    #[test]
    fn parse_messages_stops_silently_when_declared_length_exceeds_buffer() {
        let mut body = Vec::new();
        body.extend_from_slice(&10u16.to_be_bytes()); // claims 10 bytes follow
        body.extend_from_slice(b"only3"); // but only 5 are present

        let mut calls = 0;
        parse_messages(&body, 1, |_| calls += 1);
        assert_eq!(calls, 0);
    }

    #[test]
    fn parse_messages_stops_after_partial_success_on_truncation() {
        // one good message, then a second block whose length prefix is cut off
        let mut body = message_block(b"good");
        body.push(0); // half a length prefix

        let mut seen = Vec::new();
        parse_messages(&body, 2, |msg| seen.push(msg.to_vec()));

        assert_eq!(seen, vec![b"good".to_vec()]);
    }

    // ---- Session ----

    #[test]
    fn first_packet_reports_new_session_with_no_previous() {
        let mut session = Session::new();
        let header = MoldUDP64PacketHeader { session: session_id(1), sequence_number: 100, message_count: 5 };

        let status = session.on_packet(&header);

        assert_eq!(status, PacketStatus::NewSession { previous: None });
        assert_eq!(session.expected_sequence_number, 105);
    }

    #[test]
    fn in_order_packet_advances_expected_sequence_number() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 });

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 5, message_count: 3 });

        assert_eq!(status, PacketStatus::InOrder);
        assert_eq!(session.expected_sequence_number, 8);
    }

    #[test]
    fn heartbeat_with_matching_sequence_is_in_order_and_does_not_advance() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 });

        // heartbeat: message_count 0, sequence_number == next expected
        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 5, message_count: 0 });

        assert_eq!(status, PacketStatus::InOrder);
        assert_eq!(session.expected_sequence_number, 5);
    }

    #[test]
    fn gap_reports_start_and_count_and_advances_past_it() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5 next

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 10, message_count: 2 });

        assert_eq!(status, PacketStatus::Gap { start: 5, count: 5 });
        assert_eq!(session.expected_sequence_number, 12);
    }

    #[test]
    fn stale_or_duplicate_does_not_move_expected_sequence_number() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5 next

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 });

        assert_eq!(status, PacketStatus::StaleOrDuplicate);
        assert_eq!(session.expected_sequence_number, 5);
    }

    #[test]
    fn end_of_session_does_not_move_expected_sequence_number() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5 next

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 5, message_count: 0xFFFF });

        assert_eq!(status, PacketStatus::EndOfSession);
        assert_eq!(session.expected_sequence_number, 5);
    }

    #[test]
    fn session_change_mid_stream_reports_previous_and_reseeds_expected() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 });

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(2), sequence_number: 50, message_count: 2 });

        assert_eq!(status, PacketStatus::NewSession { previous: Some(session_id(1)) });
        assert_eq!(session.expected_sequence_number, 52);
    }

    #[test]
    fn first_packet_being_end_of_session_does_not_corrupt_expected_sequence_number() {
        let mut session = Session::new();
        let status = session.on_packet(&MoldUDP64PacketHeader {
            session: session_id(1), sequence_number: 100, message_count: 0xFFFF,
        });

        assert_eq!(status, PacketStatus::NewSession { previous: None });
        assert_eq!(session.expected_sequence_number, 100); // not 100 + 65535
    }

    #[test]
    fn new_sessions_first_packet_being_end_of_session_does_not_corrupt_expected_sequence_number() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 });

        let status = session.on_packet(&MoldUDP64PacketHeader {
            session: session_id(2), sequence_number: 200, message_count: 0xFFFF,
        });

        assert_eq!(status, PacketStatus::NewSession { previous: Some(session_id(1)) });
        assert_eq!(session.expected_sequence_number, 200);
    }

    #[test]
    fn end_of_session_takes_priority_over_gap_and_stale_sequence_values() {
        let mut ahead = Session::new();
        ahead.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5
        assert_eq!(
            ahead.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 50, message_count: 0xFFFF }),
            PacketStatus::EndOfSession
        );

        let mut behind = Session::new();
        behind.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5
        assert_eq!(
            behind.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 2, message_count: 0xFFFF }),
            PacketStatus::EndOfSession
        );
    }

    #[test]
    fn heartbeat_ahead_of_expected_reports_gap() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 9, message_count: 0 });

        assert_eq!(status, PacketStatus::Gap { start: 5, count: 4 });
        assert_eq!(session.expected_sequence_number, 9);
    }

    #[test]
    fn duplicate_heartbeat_is_stale_and_does_not_advance() {
        let mut session = Session::new();
        session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 1, message_count: 4 }); // expects 5

        let status = session.on_packet(&MoldUDP64PacketHeader { session: session_id(1), sequence_number: 3, message_count: 0 });

        assert_eq!(status, PacketStatus::StaleOrDuplicate);
        assert_eq!(session.expected_sequence_number, 5);
    }
}
// </Generated by Claude.ai>