use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};
use std::net::{Ipv4Addr, ToSocketAddrs, UdpSocket};
use std::path::Path;

pub trait PacketSource {
    fn next_packet(&mut self) -> std::io::Result<Option<Vec<u8>>>;
}

pub struct FilePacketSource {
    reader: BufReader<File>,
}

impl FilePacketSource {
    pub fn open(path: impl AsRef<Path>) -> std::io::Result<Self> {
        let file = File::open(path)?;
        Ok(Self { reader: BufReader::new(file) })
    }
}

impl PacketSource for FilePacketSource {
    fn next_packet(&mut self) -> std::io::Result<Option<Vec<u8>>> {
        let mut length_buf = [0u8; 4];

        match self.reader.read_exact(&mut length_buf) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => return Ok(None),
            Err(e) => return Err(e),
        }

        let packet_length = u32::from_be_bytes(length_buf) as usize;
        let mut packet = vec![0u8; packet_length];
        self.reader.read_exact(&mut packet)?;

        Ok(Some(packet))
    }
}

const MAX_UDP_DATAGRAM_SIZE: usize = 65_536;

pub struct UdpPacketSource {
    socket: UdpSocket,
}

impl UdpPacketSource {
    pub fn join_multicast(
        multicast_addr: Ipv4Addr,
        port: u16,
        interface: Ipv4Addr,
    ) -> std::io::Result<Self> {
        let socket = UdpSocket::bind((Ipv4Addr::UNSPECIFIED, port))?;
        socket.join_multicast_v4(&multicast_addr, &interface)?;
        Ok(Self { socket })
    }

    pub fn bind(addr: impl ToSocketAddrs) -> std::io::Result<Self> {
        Ok(Self { socket: UdpSocket::bind(addr)? })
    }
}

impl PacketSource for UdpPacketSource {
    fn next_packet(&mut self) -> std::io::Result<Option<Vec<u8>>> {
        let mut buf = vec![0u8; MAX_UDP_DATAGRAM_SIZE];
        let (received, _origin) = self.socket.recv_from(&mut buf)?;
        buf.truncate(received);
        Ok(Some(buf))
    }
}

pub fn write_packets_to_file(path: impl AsRef<Path>, packets: &[Vec<u8>]) -> std::io::Result<()> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    for packet in packets {
        let length = u32::try_from(packet.len()).expect("packet length exceeds u32::MAX");
        writer.write_all(&length.to_be_bytes())?;
        writer.write_all(packet)?;
    }

    writer.flush()
}

// <Generated by Claude.ai>
#[cfg(test)]
mod tests {
    use super::*;
    use crate::build_packet;
    use std::io::Write;

    fn write_framed_packet(writer: &mut impl Write, packet: &[u8]) -> std::io::Result<()> {
        let length = u32::try_from(packet.len()).expect("packet length exceeds u32::MAX");
        writer.write_all(&length.to_be_bytes())?;
        writer.write_all(packet)
    }

    struct TempFileGuard(std::path::PathBuf);

    impl Drop for TempFileGuard {
        fn drop(&mut self) {
            let _ = std::fs::remove_file(&self.0);
        }
    }

    #[test]
    fn file_packet_source_round_trips_multiple_packets_in_order() {
        let session = *b"SESSION001";
        let original_packets = vec![
            build_packet(session, 1, &[b"MSG_A", b"MSG_B"]),
            build_packet(session, 3, &[b"MSG_C"]),
            build_packet(session, 4, &[]), // heartbeat: zero messages
        ];

        let path = std::env::temp_dir()
            .join(format!("moldudp64_fixture_{}.bin", std::process::id()));
        let _guard = TempFileGuard(path.clone());

        {
            let file = std::fs::File::create(&path).expect("should create fixture file");
            let mut writer = std::io::BufWriter::new(file);
            for packet in &original_packets {
                write_framed_packet(&mut writer, packet).expect("should write packet");
            }
            writer.flush().expect("should flush fixture file to disk");
        }

        let mut source = FilePacketSource::open(&path).expect("should open fixture file");

        for expected in &original_packets {
            let actual = source
                .next_packet()
                .expect("should read without I/O error")
                .expect("should yield a packet, not None");
            assert_eq!(&actual, expected);
        }

        assert_eq!(
            source.next_packet().expect("should read without I/O error"),
            None,
            "source should report exhaustion after the last real packet"
        );
    }
}
// </Generated by Claude.ai>